CREATE TABLE IF NOT EXISTS `vessels` (
  `MessageType` DECIMAL(11) DEFAULT NULL, 
  `MMSI` DECIMAL(11) NOT NULL DEFAULT '0',
  `NavStatus` varchar(128) DEFAULT NULL,
  `ROT` double DEFAULT NULL,
  `SOG` double DEFAULT NULL,
  `LON` float DEFAULT NULL,
  `LAT` float DEFAULT NULL,
  `COG` double DEFAULT NULL,
  `true_heading` double DEFAULT NULL,
  `DateTime` DECIMAL(20) DEFAULT NULL, 
  `IMO` DECIMAL(11) DEFAULT NULL,
  `VesselName` varchar(128) DEFAULT NULL,
  `VesselTypeInt` DECIMAL(11) DEFAULT NULL,
  `Length` double DEFAULT NULL,
  `shipWidth` DECIMAL(11) DEFAULT NULL, 
  `Bow` DECIMAL(11) DEFAULT NULL, 
  `Stern` DECIMAL(11) DEFAULT NULL, 
  `Port` DECIMAL(11) DEFAULT NULL, 
  `Starboard` DECIMAL(11) DEFAULT NULL, 
  `Draught` DECIMAL(11) DEFAULT NULL, 
  `Destination` VARCHAR(128) DEFAULT NULL, 
  `Callsign` VARCHAR(128) DEFAULT NULL, 
  `PosAccuracy` DECIMAL(11) DEFAULT NULL, 
  `ETA` NUMBER(11) DEFAULT NULL, 
  `PosFixType` DECIMAL(11) DEFAULT NULL,
  `STREAMID` VARCHAR(36) DEFAULT NULL,
  KEY `MMSI` (`MMSI`), 
  KEY `LAT` (`LAT`),
  KEY `LON` (`LON`),
  KEY `DateTime` (`DateTime`),
  KEY `VesselName` (`VesselName`),
  KEY `VesselTypeInt` (`VesselTypeInt`),
  KEY `STREAMID` (`STREAMID`),
  KEY `IMO` (`IMO`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


